### ISSUE TITLE
不能支持多个注册中心

### ISSUE THREAD

**Issue by longye321** [alibaba/spring-boot-starter-dubbo#10]
在application.properties中配置zookeeper的多个注册中心，按照以前的思路，多个注册中心用英文逗号（，）隔开，但会出现java.lang.NumberFormatException异常
进入源码查看，发现问题是没有解决分隔符，改成“|”，但又出现别的错误

**Comment by longye321** [comment]
问题已经解决，格式没写对，看了一下官方文档
zookeeper://10.20.153.10:2181?backup=10.20.153.11:2181,10.20.153.12:2181

**Comment by zhangqijia** [comment]
Hi，兄弟，官方文档的链接能提供一个吗，在readme里没有找到这种配置

**Comment by niomac** [comment]
> 问题已经解决，格式没写对，看了一下官方文档
> zookeeper://10.20.153.10:2181?backup=10.20.153.11:2181,10.20.153.12:2181

这是配置zookeeper集群吧，我是想知道怎么配置多个不同的zookeeper集群
