### ISSUE TITLE
方法级的配置，怎么实现

### ISSUE THREAD

**Issue by longye321** [alibaba/spring-boot-starter-dubbo#12]
<dubbo:method/> 这个配置，是否支持

**Comment by longye321** [comment]
不写dubbo的xml配置的情况下，应该怎么指定接口中，某个方法为异步方法，并且不需要返回值

**Comment by xionghuiCoder** [comment]
dubbo:method/ 这个配置还没支持的；
异步方法试下@DubboConsumer的async参数配置；

**Comment by longye321** [comment]
这个我也看了，如果配置@dubboconsumer的async参数，这个会导致整个服务下的方法都变成异步的，所以不可用
