### ISSUE TITLE
请问全局的check=false 怎么配置？spring.dubbo.check=false?

### ISSUE THREAD

**Issue by liuxianshengCn** [alibaba/spring-boot-starter-dubbo#13]
怎么避免provider不存在时，所抛出异常影响其他功能使用。

**Comment by xionghuiCoder** [comment]
目前并不支持全局check配置,但是可以通过单个接口的配置来设置check,类似:
@DubboConsumer(timeout = 1000, check = false)

**Comment by liuxianshengCn** [comment]
啥时候出RELEASE版本。。还有就是 现在使用maven打包好像有点问题。maven无法下载jar包

**Comment by xionghuiCoder** [comment]
目前没有release计划,需要clone到本地仓库打包发布
