### ISSUE TITLE
节点无法注册到zookeeper中

### ISSUE THREAD

**Issue by tkzandgj** [alibaba/spring-boot-starter-dubbo#16]
spring:
  dubbo:
    appname: spring-boot-starter-dubbo-provider-test
    registry: zookeeper://127.0.0.1:2181?backup=127.0.0.1:2182,127.0.0.1:2183
    protocol: dubbo
我的springboot的配置是这样的，但是节点一直没有注册成功，导致服务不可用，这是为什么呢？

**Comment by tkzandgj** [comment]
问题已经解决，少加了一个spring的注解，导致没有扫描到没有注册节点信息到zookeeper中。

**Comment by xionghuiCoder** [comment]
FYI

**Comment by TriMea** [comment]
缺少了哪个spring注解，请明示
