### ISSUE TITLE
是否可以加载dubbo的xml配置文件呢

### ISSUE THREAD

**Issue by tkzandgj** [alibaba/spring-boot-starter-dubbo#23]
请问这个现在在springboot的项目中应用的话是不是不能通过@ImportResource去加载dubbo的xml配置文件呢？？

**Comment by xionghuiCoder** [comment]
@ImportResource是spring的feature, 只要dubbo支持就ok的, 和springboot是没有关系的

**Comment by tkzandgj** [comment]
我要是把.properies或者.yml里面的配置文件全都注释掉，只在xml里面加上<dubbo>标签，好像是加载不到的
