### ISSUE TITLE
配置zookeeper

### ISSUE THREAD

**Issue by Daily1116** [alibaba/spring-boot-starter-dubbo#27]
怎么配置多个zookeeper地址，例如：zookeeper://172.16.37.112:2181,172.16.37.112:2182,172.16.37.112:2183

**Comment by xionghuiCoder** [comment]
hi,请尝试下以下三种方式：zookeeper://172.16.37.112:2181?backup=172.16.37.112:2182,172.16.37.112:2183或者172.16.37.112:2181,172.16.37.112:2182,172.16.37.112:2183或者zookeeper://172.16.37.112:2181,172.16.37.112:2182,172.16.37.112:2183
