### ISSUE TITLE
该项目目前是否处于可用状态？

### ISSUE THREAD

**Issue by tywo45** [alibaba/spring-boot-starter-dubbo#3]
我准备在项目中用spring-boot-starter-dubbo，但github上找了好几个，发现这个是阿里title的，但却又是快照版。所以想知道该项目目前是否处于可用状态？谢谢作者！

**Comment by eonezhang** [comment]
no update

**Comment by xionghuiCoder** [comment]
目前还无发布到中央仓库的计划, 但是是经过线上验证的,请知晓
