### ISSUE TITLE
依赖无法添加

### ISSUE THREAD

**Issue by leyou240** [alibaba/spring-boot-starter-dubbo#30]
<dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>spring-boot-starter-dubbo</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </dependency>

以上依赖在maven仓库未找到。另外在[阿里的仓库](http://maven.aliyun.com/nexus/#nexus-search;quick~spring-boot-starter-dubbo)中也未找到

**Comment by xionghuiCoder** [comment]
hi，目前没有发布release，发的snapshot；请知晓

**Comment by wzh154710510** [comment]
您好，快照版本的也未找到
