### ISSUE TITLE
不支持接入多个provider

### ISSUE THREAD

**Issue by gaowenming** [alibaba/spring-boot-starter-dubbo#5]
作为consumer，接入多个provider的时候，发现appname不能支持多个，也就是只能接一个服务提供方了，请问后续有对多个provider接入的支持吗？

**Comment by xionghuiCoder** [comment]
spring.dubbo.appname配置的是consumer的应用名称,  与支持多个provider不冲突的, 如果需要接入多个provider只需接入@DubboConsumer配置既可

**Comment by gaowenming** [comment]
@ConfigurationProperties(prefix = "spring.dubbo")
public class DubboProperties {
  /**
   * dubbo application name
   */
  private String appname;
  /**
   * dubbo registry address
   */
  private String registry;

DubboProperties 中定义的属性名称，如果接入多个provider，如下的属性中registry地址是可能不同，这样的话，怎么处理？

spring.dubbo.appname=spring-boot-starter-dubbo-consumer-test
**spring.dubbo.registry=multicast://224.0.0.0:1111**
spring.dubbo.protocol=dubbo

**Comment by xionghuiCoder** [comment]
尝试设置下＠DubboConsumer的registry
