### ISSUE TITLE
请问 maven 的依赖应该使用哪个 repo？

### ISSUE THREAD

**Issue by magicliang** [alibaba/spring-boot-starter-dubbo#6]
maven 的中心 repo 搜不到记录。
编译报错：

Could not find artifact com.alibaba:spring-boot-starter-dubbo:jar:1.0.0-SNAPSHOT -> [Help 1]

**Comment by xiaoshuaishuai** [comment]
把源码clone下来，自己打个包放私服上不就好了。

**Comment by magicliang** [comment]
我现在确实就是这么做的。但我总觉得是权宜之计。我以为这个东西至少会发布到阿里云的 repo 上才对。

**Comment by xionghuiCoder** [comment]
hi, 目前并没有发布计划，请知晓
